/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package team8;

import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author sam
 */
public class Dashboard extends javax.swing.JFrame {
    private static Dashboard _instance = null;
    public static String sortType;
    
    private static Point lastPnlDocumentClick = null;
    /**
     * Creates new form Dashboard
     */
    private Dashboard() {
        initComponents();
    }
    
    public static Dashboard getInstance() {
        if (_instance == null) {
            _instance = new Dashboard();
        }
        
        return _instance;
    }
    
    public void display() {
        Util.setFrameInMiddle(this);
        setVisible(true);
        this.comboSortType.removeAllItems();
        this.comboSortType.addItem("Date Added");
        this.comboSortType.addItem("Name");
        this.comboSortType.setSelectedItem("Name");
        
        sortType = "Name";
        
        updateClientList();
        
        this.lblClientName.setVisible(false);
        this.lblClientSince.setVisible(false);
        this.txtAge.setVisible(false);
        this.txtGender.setVisible(false);
        this.txtIncome.setVisible(false);
        this.txtMarital.setVisible(false);
    }
    
    public void updateClientList() {
        updateClientList("");
    }
    
    public void updateClientList(String filter) {
        Client[] clist = FakeDB.getClientList();
        
        if (filter == null) {
            filter = "";
        }
        
        this.lstClientList.removeAll();
        String[] names = new String[clist.length];
        int lstInd = 0;
        for (int i = 0; i < clist.length; i++) {
            if (!filter.equals("")
                    && !clist[i].getName().toLowerCase().contains(filter.toLowerCase())) {
                
                continue;
            }
            
            names[lstInd] = clist[i].getName();
            lstInd++;
        }
        
        this.txtSearchClient.setText(null);
        this.lstClientList.setListData(names);
        this.lstClientList.repaint();
    }
    
    public void updateDocumentList(String name) {
        updateDocumentList(name, "");
    }
    
    public void updateDocumentList(String name, String filter) {
        Document[] dlist = FakeDB.getDocumentsByClient(name, (String)this.comboSortType.getSelectedItem());
        
        this.pnlDocumentList.removeAll();
        
        if (filter == null) {
            filter = "";
        }
        
        // Document list
        ArrayList<DocumentPanel> panelsToAdd = new ArrayList<>();
        for (int i = 0; i < dlist.length; i++) {
            DocumentPanel p = new DocumentPanel(dlist[i]);
            if (!filter.equals("")
                    && !p.getDocument().getName().toLowerCase().contains(filter.toLowerCase())) {
                continue;
            }
            
            panelsToAdd.add(p);
        }
        
        GridBagLayout g = new GridBagLayout();
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.NORTH;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.insets = new Insets(3,3,3,3);
        
        this.pnlDocumentList.setLayout(g);
        
        for (int i = 0; i < panelsToAdd.size(); i++) {
            c.gridy = i;
            if ( i == panelsToAdd.size() - 1) {
                c.weighty = 1.0;
            }
            
            DocumentPanel dp = panelsToAdd.get(i);
            g.setConstraints(dp, c);
            this.pnlDocumentList.add(dp);
        }
        
        for (int i = 0; i < this.pnlDocumentList.getComponentCount(); i++) {
            this.pnlDocumentList.getComponent(i).doLayout();
        }
        
        this.pnlDocumentList.doLayout();
        this.scrpnlDocuments.doLayout();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpnlClients = new javax.swing.JTabbedPane();
        tabActive = new javax.swing.JPanel();
        btnFilterClients = new javax.swing.JButton();
        txtSearchClient = new javax.swing.JTextField();
        scrpnlClientList = new javax.swing.JScrollPane();
        lstClientList = new javax.swing.JList();
        tabInactive = new javax.swing.JPanel();
        pnlLoadingFiles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSync = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnNewClient = new javax.swing.JButton();
        btnNewDocument = new javax.swing.JButton();
        txtSearchDocument = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        scrpnlDocuments = new javax.swing.JScrollPane();
        pnlDocumentList = new javax.swing.JPanel();
        scrpnlDocumentView = new javax.swing.JScrollPane();
        pnlDocumentView = new javax.swing.JPanel();
        comboSortType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        pnlClientInfo = new javax.swing.JPanel();
        lblClientName = new javax.swing.JLabel();
        lblClientSince = new javax.swing.JLabel();
        btnEditClient = new javax.swing.JButton();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtIncome = new javax.swing.JTextField();
        txtMarital = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Records Management System");

        btnFilterClients.setText("Filter Clients by...");

        txtSearchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchClientKeyReleased(evt);
            }
        });

        lstClientList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstClientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstClientListMouseClicked(evt);
            }
        });
        scrpnlClientList.setViewportView(lstClientList);

        javax.swing.GroupLayout tabActiveLayout = new javax.swing.GroupLayout(tabActive);
        tabActive.setLayout(tabActiveLayout);
        tabActiveLayout.setHorizontalGroup(
            tabActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFilterClients, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
            .addComponent(txtSearchClient)
            .addComponent(scrpnlClientList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        tabActiveLayout.setVerticalGroup(
            tabActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabActiveLayout.createSequentialGroup()
                .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpnlClientList, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilterClients))
        );

        tabpnlClients.addTab("Active Clients", tabActive);

        javax.swing.GroupLayout tabInactiveLayout = new javax.swing.GroupLayout(tabInactive);
        tabInactive.setLayout(tabInactiveLayout);
        tabInactiveLayout.setHorizontalGroup(
            tabInactiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        tabInactiveLayout.setVerticalGroup(
            tabInactiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        tabpnlClients.addTab("Inactive Clients", tabInactive);

        pnlLoadingFiles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlLoadingFilesLayout = new javax.swing.GroupLayout(pnlLoadingFiles);
        pnlLoadingFiles.setLayout(pnlLoadingFilesLayout);
        pnlLoadingFilesLayout.setHorizontalGroup(
            pnlLoadingFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLoadingFilesLayout.setVerticalGroup(
            pnlLoadingFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel1.setText("Last Sync: Jul 20, 2012 20:31");

        btnSync.setBackground(new java.awt.Color(254, 254, 254));
        btnSync.setForeground(new java.awt.Color(254, 254, 254));
        btnSync.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team8/image/sync icon.png"))); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnNewClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team8/image/client icon.png"))); // NOI18N

        btnNewDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team8/image/document icon.png"))); // NOI18N
        btnNewDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDocumentActionPerformed(evt);
            }
        });

        txtSearchDocument.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchDocumentKeyReleased(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSync, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSync, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(btnNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNewDocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchDocument)
                .addContainerGap())
            .addComponent(jSeparator2)
        );

        pnlDocumentList.setBackground(new java.awt.Color(254, 254, 254));
        pnlDocumentList.setMinimumSize(new java.awt.Dimension(10, 100));
        pnlDocumentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDocumentListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDocumentListLayout = new javax.swing.GroupLayout(pnlDocumentList);
        pnlDocumentList.setLayout(pnlDocumentListLayout);
        pnlDocumentListLayout.setHorizontalGroup(
            pnlDocumentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        pnlDocumentListLayout.setVerticalGroup(
            pnlDocumentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        scrpnlDocuments.setViewportView(pnlDocumentList);

        javax.swing.GroupLayout pnlDocumentViewLayout = new javax.swing.GroupLayout(pnlDocumentView);
        pnlDocumentView.setLayout(pnlDocumentViewLayout);
        pnlDocumentViewLayout.setHorizontalGroup(
            pnlDocumentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        pnlDocumentViewLayout.setVerticalGroup(
            pnlDocumentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        scrpnlDocumentView.setViewportView(pnlDocumentView);

        comboSortType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSortType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Sort by:");

        pnlClientInfo.setBackground(new java.awt.Color(254, 254, 254));
        pnlClientInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(158, 158, 158), 1, true));
        pnlClientInfo.setPreferredSize(new java.awt.Dimension(50, 50));

        lblClientName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblClientName.setText("jLabel3");

        lblClientSince.setText("jLabel3");

        btnEditClient.setText("Edit");
        btnEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientActionPerformed(evt);
            }
        });

        txtGender.setEditable(false);
        txtGender.setText("jTextField1");
        txtGender.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(115, 115, 115), null));

        txtAge.setEditable(false);
        txtAge.setText("jTextField2");
        txtAge.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(115, 115, 115), null));

        txtIncome.setEditable(false);
        txtIncome.setText("jTextField3");
        txtIncome.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(115, 115, 115), null));

        txtMarital.setEditable(false);
        txtMarital.setText("jTextField4");
        txtMarital.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(115, 115, 115), null));

        javax.swing.GroupLayout pnlClientInfoLayout = new javax.swing.GroupLayout(pnlClientInfo);
        pnlClientInfo.setLayout(pnlClientInfoLayout);
        pnlClientInfoLayout.setHorizontalGroup(
            pnlClientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientInfoLayout.createSequentialGroup()
                .addGroup(pnlClientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientInfoLayout.createSequentialGroup()
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientInfoLayout.createSequentialGroup()
                        .addComponent(lblClientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClientSince)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlClientInfoLayout.setVerticalGroup(
            pnlClientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientInfoLayout.createSequentialGroup()
                .addGroup(pnlClientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientName)
                    .addComponent(lblClientSince))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(btnEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlClientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabpnlClients, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(scrpnlDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(3, 3, 3)
                                        .addComponent(comboSortType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrpnlDocumentView))
                            .addComponent(pnlClientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)))
                    .addComponent(pnlLoadingFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlClientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboSortType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrpnlDocuments))
                            .addComponent(scrpnlDocumentView)))
                    .addComponent(tabpnlClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLoadingFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSortTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortTypeActionPerformed
        if (this.comboSortType.getItemCount() == 0 || this.lstClientList.getModel().getSize() == 0) {
            return;
        }
        
        updateDocumentList((String)this.lstClientList.getSelectedValue());
    }//GEN-LAST:event_comboSortTypeActionPerformed

    private void lstClientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstClientListMouseClicked
        updateDocumentList((String)this.lstClientList.getSelectedValue());
        
        Client c = FakeDB.getClient((String)this.lstClientList.getSelectedValue());
        if (c == null) {
            return;
        }
        
        this.lblClientName.setText(" " + c.getName());
        this.lblClientSince.setText("Client Since " + c.getSince());
        this.txtAge.setText("  Age: " + c.getAge() + "  ");
        this.txtGender.setText("  Gender: " + c.getGender() + "  ");
        this.txtIncome.setText("  Income: " + c.getIncome() + "  ");
        this.txtMarital.setText("  Marital: " + c.getMarital() + "  ");        
        
        this.pnlDocumentView.removeAll();
        
        for (int i = 0; i < this.pnlClientInfo.getComponentCount(); i++) {
            this.pnlClientInfo.getComponent(i).setVisible(true);
        }
        this.pnlClientInfo.doLayout();
        
        this.pnlDocumentView.doLayout();
        this.scrpnlDocumentView.doLayout();
    }//GEN-LAST:event_lstClientListMouseClicked

    private void txtSearchClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchClientKeyReleased
        updateClientList(txtSearchClient.getText());
    }//GEN-LAST:event_txtSearchClientKeyReleased

    private void pnlDocumentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentListMouseClicked
        Point thisClick = evt.getPoint();
        
        Component c = this.pnlDocumentList.getComponentAt(thisClick);
        if (!c.getClass().getName().equals("team8.DocumentPanel")) {
            return;
        }
        
        DocumentPanel dp = (DocumentPanel)c;
        
        dp.setBackground(Color.white);
        
        if (lastPnlDocumentClick != null) {
            this.pnlDocumentList.getComponentAt(lastPnlDocumentClick).setBackground(new Color(238, 238, 238));
        }
        
        lastPnlDocumentClick = thisClick;
        
        this.pnlDocumentView.removeAll();
        
        this.pnlDocumentView.setLayout(new GridLayout(1,1));
        DocumentView dv = new DocumentView(dp.getDocument());
        
        this.pnlDocumentView.add(dv);
        
        this.scrpnlDocumentView.doLayout();
        this.pnlDocumentView.doLayout();
        dv.doLayout();
        
        this.scrpnlDocumentView.repaint();
    }//GEN-LAST:event_pnlDocumentListMouseClicked

    private void txtSearchDocumentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDocumentKeyReleased
        updateDocumentList((String)lstClientList.getSelectedValue(), this.txtSearchDocument.getText());
    }//GEN-LAST:event_txtSearchDocumentKeyReleased

    private void btnNewDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDocumentActionPerformed
        new NewDocument(this, true).setVisible(true);
    }//GEN-LAST:event_btnNewDocumentActionPerformed

    private void btnEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientActionPerformed
        Client c = FakeDB.getClient((String)this.lstClientList.getSelectedValue());
        
        if (c == null) {
            return;
        }
        
        new ModifyClient(this, true, c).setVisible(true);
    }//GEN-LAST:event_btnEditClientActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditClient;
    private javax.swing.JButton btnFilterClients;
    private javax.swing.JButton btnNewClient;
    private javax.swing.JButton btnNewDocument;
    private javax.swing.JButton btnSync;
    private javax.swing.JComboBox comboSortType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblClientSince;
    private javax.swing.JList lstClientList;
    private javax.swing.JPanel pnlClientInfo;
    private javax.swing.JPanel pnlDocumentList;
    private javax.swing.JPanel pnlDocumentView;
    private javax.swing.JPanel pnlLoadingFiles;
    private javax.swing.JScrollPane scrpnlClientList;
    private javax.swing.JScrollPane scrpnlDocumentView;
    private javax.swing.JScrollPane scrpnlDocuments;
    private javax.swing.JPanel tabActive;
    private javax.swing.JPanel tabInactive;
    private javax.swing.JTabbedPane tabpnlClients;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtMarital;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JTextField txtSearchDocument;
    // End of variables declaration//GEN-END:variables
}
