/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package team8;

import java.awt.Dimension;

/**
 *
 * @author sam
 */
public class DocumentPanel extends javax.swing.JPanel {
    private Document doc = null;

    /**
     * Creates new form DocumentPanel
     */
    public DocumentPanel(Document d) {
        initComponents();
        
        this.doc = d;
        this.lblDocumentName.setText(d.getName());
        this.lblDateAdded.setText(d.getDateAdded());
    }
    
    public Document getDocument() {
        return this.doc;
    }
    
    public void setDocumentName(String txt) {
        this.lblDocumentName.setText(txt);
    }
    
    public void setDateAdded(String d) {
        this.lblDateAdded.setText(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDocumentName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDateAdded = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 125, 125), 1, true));
        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(0, 100));
        setName("");
        setPreferredSize(new java.awt.Dimension(230, 100));

        lblDocumentName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDocumentName.setText("Document Name");

        lblDateAdded.setText("Date Added");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDocumentName)
                            .addComponent(lblDateAdded))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocumentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateAdded)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDateAdded;
    private javax.swing.JLabel lblDocumentName;
    // End of variables declaration//GEN-END:variables
}
